package execenv

import (
	"fmt"
	"log/slog"
	"os"
	"regexp"
	"strings"
)


const AgentaCodexMultiAgentEnv = "AGENTA_CODEX_MULTI_AGENT"

// agentaMultiAgentBeginMarker / agentaMultiAgentEndMarker delimit the
// multi-agent-specific managed block. Kept separate from the sandbox
// block so each can evolve and migrate independently.
const (
	agentaMultiAgentBeginMarker = "# BEGIN agenta-managed multi-agent (do not edit; regenerated by daemon)"
	agentaMultiAgentEndMarker   = "# END agenta-managed multi-agent"
)

// `\n*` rather than `\n?` so reruns don't accumulate blank lines when this
// block coexists with the sandbox managed block in the same file. The same
// regex matches the block whether it sits at the file root (dotted-key
// form) or inside a `[features]` table — only the body keys differ.
var multiAgentBlockRe = regexp.MustCompile(
	`(?ms)^` + regexp.QuoteMeta(agentaMultiAgentBeginMarker) +
		`.*?^` + regexp.QuoteMeta(agentaMultiAgentEndMarker) + `\n*`)

var (
	// matches a top-level `[features]` table header, allowing TOML's optional
	// whitespace inside brackets and inline comments after the header.
	rootFeaturesTableHeaderRe = regexp.MustCompile(`^\s*\[\s*features\s*\]\s*(?:#.*)?$`)
	// matches `multi_agent = ...` (with optional whitespace) inside a
	// `[features]` table.
	featuresTableMultiAgentRe = regexp.MustCompile(`^\s*multi_agent\s*=`)
	// matches `features.multi_agent = ...` at the TOML root (top-level
	// dotted-key form, including TOML's optional whitespace around dots).
	rootDottedMultiAgentRe = regexp.MustCompile(`^\s*features\s*\.\s*multi_agent\s*=`)
)

// codexMultiAgentEnabled reports whether the user opted into keeping Codex
// native multi-agent on for daemon-managed tasks.
func codexMultiAgentEnabled() bool {
	raw := strings.TrimSpace(os.Getenv(AgentaCodexMultiAgentEnv))
	switch strings.ToLower(raw) {
	case "1", "true", "yes", "on":
		return true
	}
	return false
}

// renderAgentaMultiAgentBlock returns the daemon-managed multi-agent
// block. The body uses `multi_agent = false` when injected inside a
// `[features]` table, and `features.multi_agent = false` otherwise.
func renderAgentaMultiAgentBlock(inFeaturesTable bool) string {
	var b strings.Builder
	b.WriteString(agentaMultiAgentBeginMarker)
	b.WriteString("\n")
	if inFeaturesTable {
		b.WriteString("multi_agent = false\n")
	} else {
		b.WriteString("features.multi_agent = false\n")
	}
	b.WriteString(agentaMultiAgentEndMarker)
	b.WriteString("\n")
	return b.String()
}

// stripUserMultiAgentDirectives removes any `features.multi_agent = ...`
// line at the TOML root (dotted-key form), plus any `multi_agent = ...`
// line that sits inside a top-level `[features]` table. Both forms encode
// the same TOML key and would conflict with the managed block.
//
// Other tables (`[features.experimental]`, `[profiles.foo]`, ...) are
// preserved untouched: they live under their own scope and don't redefine
// `features.multi_agent` at the root.
func stripUserMultiAgentDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	currentTable := "" // empty = TOML root
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if rootFeaturesTableHeaderRe.MatchString(line) {
			currentTable = "[features]"
			out = append(out, line)
			continue
		}
		if strings.HasPrefix(trimmed, "[") {
			currentTable = trimmed
			out = append(out, line)
			continue
		}
		switch currentTable {
		case "":
			if rootDottedMultiAgentRe.MatchString(trimmed) {
				continue
			}
		case "[features]":
			if featuresTableMultiAgentRe.MatchString(trimmed) {
				continue
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// hasRootFeaturesTable reports whether the file contains a top-level
// `[features]` table header. Sub-tables like `[features.experimental]` do
// NOT count: they implicitly create `features` but don't conflict with a
// root-level `features.multi_agent` dotted key.
func hasRootFeaturesTable(content string) bool {
	for _, line := range strings.Split(content, "\n") {
		if rootFeaturesTableHeaderRe.MatchString(line) {
			return true
		}
	}
	return false
}

// injectManagedBlockIntoFeaturesTable inserts the in-table managed block
// immediately after the first `[features]` header line. Caller must have
// already stripped any prior managed block and any user-set `multi_agent`
// directive from inside the table.
func injectManagedBlockIntoFeaturesTable(content string) string {
	block := renderAgentaMultiAgentBlock(true)
	// Drop the trailing `\n` so we don't introduce a stray blank line when
	// splicing block lines between existing lines.
	blockLines := strings.Split(strings.TrimRight(block, "\n"), "\n")
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if !rootFeaturesTableHeaderRe.MatchString(line) {
			continue
		}
		out := make([]string, 0, len(lines)+len(blockLines))
		out = append(out, lines[:i+1]...)
		out = append(out, blockLines...)
		out = append(out, lines[i+1:]...)
		return strings.Join(out, "\n")
	}
	return content
}

// ensureCodexMultiAgentConfig writes the daemon-managed multi-agent block
// into the per-task config.toml so Codex native subagents stay disabled.
// Idempotent: running it twice produces the same file.
//
// When AGENTA_CODEX_MULTI_AGENT is set to a truthy value, the function is
// a no-op — the user has explicitly opted into Codex native subagents and
// accepts the lifecycle risk. Toggling the env var across prepare runs is
// not supported: the per-task config is short-lived (recreated per task),
// so users should set the var once at daemon start.
func ensureCodexMultiAgentConfig(configPath string, logger *slog.Logger) error {
	if codexMultiAgentEnabled() {
		if logger != nil {
			logger.Info("codex multi-agent: leaving Codex native multi-agent untouched per AGENTA_CODEX_MULTI_AGENT",
				"config_path", configPath,
			)
		}
		return nil
	}

	data, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read config.toml: %w", err)
	}
	existing := string(data)

	// Always strip any previously written managed block (root or in-table
	// form) so reruns and layout transitions stay clean.
	existing = multiAgentBlockRe.ReplaceAllString(existing, "")
	// Strip user-set directives in both encodings; the managed block re-adds
	// the canonical form below.
	existing = stripUserMultiAgentDirectives(existing)

	var updated string
	if hasRootFeaturesTable(existing) {
		updated = injectManagedBlockIntoFeaturesTable(existing)
	} else {
		existing = strings.TrimLeft(existing, "\n")
		block := renderAgentaMultiAgentBlock(false)
		if existing == "" {
			updated = block
		} else {
			updated = block + "\n" + existing
		}
	}

	if updated == string(data) {
		return nil
	}

	if err := os.WriteFile(configPath, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("write config.toml: %w", err)
	}
	return nil
}
